USE [master]
GO

/****** Object:  Database [lukyanenko]    Script Date: 14.02.2024 10:18:42 ******/
DROP DATABASE [lukyanenko]
GO

/****** Object:  Database [lukyanenko]    Script Date: 14.02.2024 10:18:42 ******/
CREATE DATABASE [lukyanenko]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Справочник аптекаря Лукьяненко', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Справочник аптекаря Лукьяненко.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Справочник аптекаря Лукьяненко_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Справочник аптекаря Лукьяненко_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [lukyanenko].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [lukyanenko] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [lukyanenko] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [lukyanenko] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [lukyanenko] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [lukyanenko] SET ARITHABORT OFF 
GO

ALTER DATABASE [lukyanenko] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [lukyanenko] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [lukyanenko] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [lukyanenko] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [lukyanenko] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [lukyanenko] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [lukyanenko] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [lukyanenko] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [lukyanenko] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [lukyanenko] SET  DISABLE_BROKER 
GO

ALTER DATABASE [lukyanenko] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [lukyanenko] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [lukyanenko] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [lukyanenko] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [lukyanenko] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [lukyanenko] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [lukyanenko] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [lukyanenko] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [lukyanenko] SET  MULTI_USER 
GO

ALTER DATABASE [lukyanenko] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [lukyanenko] SET DB_CHAINING OFF 
GO

ALTER DATABASE [lukyanenko] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [lukyanenko] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [lukyanenko] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [lukyanenko] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [lukyanenko] SET QUERY_STORE = OFF
GO

ALTER DATABASE [lukyanenko] SET  READ_WRITE 
GO

